//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas.ConceptualModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumeroCorrelativo
    {
        public int Id { get; set; }
        public Nullable<int> UltimoNumero { get; set; }
        public Nullable<int> CantidadDigitos { get; set; }
        public string Gestion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    }
}
