//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas.ConceptualModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public string CodigoBarra { get; set; }
        public string Marca { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> Stock { get; set; }
        public string UrlImagen { get; set; }
        public string NombreImagen { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> IdUsuarioMod { get; set; }
        public Nullable<int> IdUsuarioElimino { get; set; }
        public Nullable<System.DateTime> FechaElimino { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
