//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas.ConceptualModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public int Id { get; set; }
        public string NumeroVenta { get; set; }
        public Nullable<int> IdTipoDocumentoVenta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string CocumentoCliente { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> ImpuestoTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuarioCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
        public virtual TipoDocumentoVenta TipoDocumentoVenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
